### ISSUE TITLE
Handle gzipped input

### ISSUE THREAD

**Issue by flashton2003** [sanger-pathogens/assembly-stats#12]
Hello,

It would be nice if assembly-stats could handle gzipped input files.

Best,

Phil

**Comment by flashton2003** [comment]
Haha, just came here to say this again.

**Comment by martinghunt** [comment]
Agree, would be nice.

You could use this workaround:
```
assembly-stats <(zcat foo.fasta.gz)
```

**Comment by flashton2003** [comment]
Ah yes, that's great, thanks Martin! Will leave open as an enhancement request.

**Comment by martinghunt** [comment]
Yep, worth leaving open! I agree would be good to support this properly.
