### ISSUE TITLE
Different output in single line vs multi line fasta

### ISSUE THREAD

**Issue by gunjanpandey** [sanger-pathogens/assembly-stats#16]
The software is giving different outputs for single vs multiline fasta. 
Seems to be counting "#lines = bytes" added into contig size 

Needs urgent fixing to avoid confusion. Or should alarm people while running the software.

**Comment by martinghunt** [comment]
Could you please provide example input files that reproduce the issue?

**Comment by gunjanpandey** [comment]
Please ignore me and accept my apologies. I was mistaken.
